name: durable-task-fanoutfanin-sample
metadata:
  template: durable-task-fanoutfanin-sample@1.0.0
services:
  client-service:
    project: ./ClientService
    language: dotnet
    host: containerapp
    docker:
      context: .
      dockerfile: ./ClientService/Dockerfile
      image: durable-task-fanoutfanin-sample/client-service:latest
  worker-service:
    project: ./WorkerService
    language: dotnet
    host: containerapp
    docker:
      context: .
      dockerfile: ./WorkerService/Dockerfile
      image: durable-task-fanoutfanin-sample/worker-service:latest