name: 💡 Feature Request
description: Suggest a new sample, pattern, or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We'd love to hear your ideas for new samples or improvements!
  - type: dropdown
    id: type
    attributes:
      label: What type of request is this?
      options:
        - New sample
        - Improvement to existing sample
        - New documentation
        - New language support
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear description of what you'd like to see.
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: What problem would this solve? Who would benefit?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or links.
